MVCDemo/Models/Challenges.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCDemo.Models
{
    [Table("tblChallengesMaster")]
    public class Challenges
    {
        public int ChallengeId { get; set; }

        public string ChallengeTitle { get; set;}

        public string ChallengeDescription { get; set; }

        public SelectList Challengelist { get; set; }

        public int SelectedValueInDropDown { get; set;}

    }
}

MVCDemo/Controllers/ChallengesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDemo.Models;
using System.Data;

namespace MVCDemo.Controllers
{
    public class ChallengesController : Controller
    {
        // GET: Challenges
        public static int chalId { get; set; }
        ChallengeContext context = new ChallengeContext();
        public ActionResult ChallengesDetails(int id)
        {

            chalId = id;
            Challenges ch = new Challenges();
           ch.ChallengeDescription = context.GetDescriptionFromOption(id);
           
            return View(ch);
        }
        
        //[HttpGet]
        //public ActionResult ChallengesDetails()
        //{
        //    Session["ChallengeId"] = ch.Challengelist.SelectedValue;
        //    return View();
        //}
        [HttpPost]
        public ActionResult ChallengesDetails(Challenges ch)
        {
            return View();
        }

        /*[HttpPost]
        public ActionResult PostSolution (int id)
        {
            return View();
        }*/

        public ActionResult ViewSolutions()
        {
            Solutions sol = new Solutions();
            //sol.SolutionList = new SelectList(challengecontext.GetSolutions(), "ChallengeId", "ChallengeDescription");
            var solGrid = context.GetSolutions();
            return View(solGrid);

        }

        [HttpPost]
        public ActionResult ViewSolutions(int id)
        {
           
            return View();

        }

        public ActionResult DisplaySolution()
        {

            return View();
        }

    }
}

MVCDemo/Views/Challenges/ChallengesDetails.cshtml
<html>

@model MVCDemo.Models.Challenges

@{
    ViewBag.Title = "ChallengesDetails";
}

<body style="background-image: url('../../Images/challen.png'); background-size: cover; color: white">
    <div>
        <br />
        <h2>Description</h2>

       <p  style="color: white"> @Html.DisplayFor(model => model.ChallengeDescription)
        </p>

        <!--onclick="@("window.location.href='" + @Url.Action("PostSolution", "PostSolution") + "'");" -->
        <!--onclick="@("window.location.href='" + @Url.Action("ViewSolutions", "Challenges") + "'");" -->
        <hr />
        <input type="button" id="btnSubmitSolution" value="Submit Your Solution " />
        <input type="button" id="btnViewSolution" value="View Solution " />
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <script language="javascript">
        //$('#ChallengeTitle').change(function () {
        //    alert($(this).val());
        //});
        $('#btnSubmitSolution').click(function () {
            window.location.href = "http://localhost:49502/PostSolution/PostSolution/";

        });

        $('#btnViewSolution').click(function () {
            window.location.href = "http://localhost:49502/Challenges/ViewSolutions/";
        });
    </script>
    </body>
</html>

MVCDemo/Views/Challenges/DisplaySolution.cshtml
<html>
@model MVCDemo.Models.Solutions

@{
    ViewBag.Title = "Display Solution";
}

<body style="background-image: url('../../Images//challen.png'); background-size: cover; color: white">

    
<div>
    <br />
    <h2>Solution</h2>

    @Html.DisplayFor(model => model.Solution)

    <p>
        Double Square Problem Analysis:
        This problem can be brute-forced (Read below for an efficient O(vM) solution). At first I thought of an approach using DP, but it would require an array of size 2147483647, which requires at least 2GB of memory (assuming each element of the array is of type unsigned char).



        Some interesting double squares. Isn’t Math beautiful?

        Unfortunately, my C++ program failed to allocate such huge amount of memory. I quickly thought of another approach using bit manipulation to store two values in each array element (ie, each occupying 4 bits, half of the size of unsigned char). Although this halved the memory usage requirement, this also means the maximum value of each element could not exceed 24 = 16, which is not true, since the largest value could go up to 64. (ie, total number of double squares for the number 1215306625 is 64.)

        The brute-force method is easy to implement and its complexity is O(M), where M is the input number. Since the input specified that N (total number of inputs) is at most 100, the brute force approach still holds, even though it might take about 30 seconds to few minutes to run.

        int doubleSquare(unsigned int m)
        {
        int total = 0;
        int iUpper = sqrt((double)m / 2.0);
        for (int i = 0; i <= iUpper; i++)
        {
        unsigned int ii = i*i;
        for (int j = i; ; j++)
        {
        unsigned int sum = ii + j*j;
        if (sum == m)
        total++;
        else if (sum > m)
        break;
        }
        }

        return total;
        }

    </p>

    <p>
        <a id="aVote" style="cursor:pointer;">
            <img src="~/Images/vote-button-md.png" height="60px" />
        </a>
        <div><b>Comment</b></div>
        <textarea rows="4" cols="50"></textarea>
    </p>

    <p align="right">
        <input type="button" id="btnBack" value="Back" />
    </p>


</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<script language="javascript">
    //$('#ChallengeTitle').change(function () {
    //    alert($(this).val());
    //});


    $('#btnBack').click(function () {
        window.location.href = "http://localhost:49502/Challenges/ViewSolutions/";
    });

    $('#aVote').click(function () {
        alert('Well done , Thanks a lot...!');
    });
</script>
    </body>
</html>

MVCDemo/Views/Challenges/ViewSolutions.cshtml
<html>

@using GridMvc.Html

@model IEnumerable<MVCDemo.Models.Solutions>

@{
    ViewBag.Title = "ViewSolutions";
}

<body style="background-color:brown; color:black">
<div>
    <br />
<h2>ViewSolutions</h2>

@Html.Grid(Model).Columns(columns =>
{
columns.Add(c => c.Name).Titled("Name");
columns.Add(c => c.Department).Titled("Team");
columns.Add(c => c.Solution).Titled("Solution")
    .Encoded(false)
    .Sanitized(false)
    .Titled("Solution Link")
     .RenderValueAs(c => Html.ActionLink("view", "DisplaySolution", "Challenges", new { id = "id1",target = "_blank"}));

})

<input type="button" id="btnBack" value="Back" onclick="@("window.location.href='" + @Url.Action("Challenges", "Home") + "'");"/>

</div>

@*<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<script language="javascript">
    //$('#ChallengeTitle').change(function () {
    //    alert($(this).val());
    //});
    $('#id1').click(function () {
        window.location.href = "http://localhost:49502/Challenges/DisplaySolutions/" ;
    });
</script>*@


</body>
</html>